from django.contrib import admin
from django.urls import re_path
from django.urls import path
#from .views import TestView
from . import views
#from .views import FriendList
#from .views import FriendDetail


urlpatterns = [
    path('',views.Login,name='Login'),
    path('Logout',views.Logout,name="Logout"),
    path('Logout2/<str:name>',views.Logout2,name="Logout2"),
    path('ADC',views.ADC,name="ADC"),
    path('editADC2/<str:name>',views.editADC2,name="editADC2"),
    path('ADC2/<str:name>',views.ADC2,name="ADC2"),
    path('PDI2/<str:name>',views.PDI2,name="PDI2"),
    path('PDI',views.PDI,name="PDI"),
    path('RH',views.RH,name="RH"),
    path('ES',views.ES,name="ES"),
    path('MBO22RH',views.MBO22RH,name="MBO22RH"),
    path('MBO22DL',views.MBO22DL,name="MBO22DL"),
    path('ADC22DL',views.ADC22DL,name="ADC22DL"),
    path('ADC22ESTA',views.ADC22ESTA,name="ADC22ESTA"),
    path('PDI22RH',views.PDI22RH,name="PDI22RH"),
    path('ADC22RHA',views.ADC22RHA,name="ADC22RHA"),
    path('upload',views.upload,name="upload"),
    path('upMBO',views.upMBO,name="upMBO"),
    path('upADC',views.upADC,name="upADC"),
    path('upPDI',views.upPDI,name="upPDI"),
    path('upCE',views.upCE,name="upCE"),
    path('upcomp',views.upcomp,name="upcomp"),
    path('listAE',views.listAE,name="listAE"),
    path('listMBO',views.listMBO,name="listMBO"),
    path('listADC',views.listADC,name="listADC"),
    path('listPDI',views.listPDI,name="listPDI"),
    path("edit4/<int:num>",views.edit4,name="edit4"),
    path("edit3/<int:num>",views.edit3,name="edit3"),
    path("edit2/<int:num>",views.edit2,name="edit2"),
    path("edit/<int:num>",views.edit,name="edit"),
    path("editADC/<int:num>",views.editADC,name="editADC"),
    path("editPDI/<int:num>",views.editPDI,name="editPDI"),
    path("home",views.home,name="home"),
    path("homeA",views.homeA,name="homeA"),
    path("homeB",views.homeB,name="homeB"),
    path("homeC",views.homeC,name="homeC"),


    path('xLogout',views.xLogout,name="xLogout"),
    path('xLogout2/<str:name>',views.xLogout2,name="xLogout2"),
    path('xADC',views.xADC,name="xADC"),
    path('xeditADC2/<str:name>',views.xeditADC2,name="xeditADC2"),
    path('xADC2/<str:name>',views.xADC2,name="xADC2"),
    path('xPDI2/<str:name>',views.xPDI2,name="xPDI2"),
    path('xPDI',views.xPDI,name="xPDI"),
    path('xES',views.xES,name="xES"),
    path('xMBO22RH',views.xMBO22RH,name="xMBO22RH"),
    path('xMBO22DL',views.xMBO22DL,name="xMBO22DL"),
    path('xADC22DL',views.xADC22DL,name="xADC22DL"),
    path('xADC22ESTA',views.xADC22ESTA,name="xADC22ESTA"),
    path('xPDI22RH',views.xPDI22RH,name="xPDI22RH"),
    path('xADC22RHA',views.xADC22RHA,name="xADC22RHA"),
    path("xedit4/<int:num>",views.xedit4,name="xedit4"),
    path("xedit3/<int:num>",views.xedit3,name="xedit3"),
    path("xedit2/<int:num>",views.xedit2,name="xedit2"),
    path("xedit/<int:num>",views.xedit,name="xedit"),
    path("xeditADC/<int:num>",views.xeditADC,name="xeditADC"),
    path("xeditPDI/<int:num>",views.xeditPDI,name="xeditPDI"),
    path("xhomeA",views.xhomeA,name="xhomeA"),
    path("xhomeB",views.xhomeB,name="xhomeB"),
    path("xhomeC",views.xhomeC,name="xhomeC"),

    path('yLogout',views.yLogout,name="yLogout"),
    path('yLogout2/<str:name>',views.yLogout2,name="yLogout2"),
    path('yADC',views.yADC,name="yADC"),
    path('yeditADC2/<str:name>',views.yeditADC2,name="yeditADC2"),
    path('yADC2/<str:name>',views.yADC2,name="yADC2"),
    path('yPDI2/<str:name>',views.yPDI2,name="yPDI2"),
    path('yPDI',views.yPDI,name="yPDI"),
    path('yES',views.yES,name="yES"),
    path('yMBO22RH',views.yMBO22RH,name="yMBO22RH"),
    path('yMBO22DL',views.yMBO22DL,name="yMBO22DL"),
    path('yADC22DL',views.yADC22DL,name="yADC22DL"),
    path('yADC22ESTA',views.yADC22ESTA,name="yADC22ESTA"),
    path('yPDI22RH',views.yPDI22RH,name="yPDI22RH"),
    path('yADC22RHA',views.yADC22RHA,name="yADC22RHA"),
    path("yedit4/<int:num>",views.yedit4,name="yedit4"),
    path("yedit3/<int:num>",views.yedit3,name="yedit3"),
    path("yedit2/<int:num>",views.yedit2,name="yedit2"),
    path("yedit/<int:num>",views.yedit,name="yedit"),
    path("yeditADC/<int:num>",views.yeditADC,name="yeditADC"),
    path("yeditPDI/<int:num>",views.yeditPDI,name="yeditPDI"),
    path("yhomeA",views.yhomeA,name="yhomeA"),
    path("yhomeB",views.yhomeB,name="yhomeB"),
    path("yhomeC",views.yhomeC,name="yhomeC"),

    path("senha",views.senha,name="senha"),

]